name: tekartik_test_menu
version: 0.0.1
homepage: https://github.com/tekartik/tekartik_test_menu.dart
# git://github.com/tekartik/tekartik_test_menu.dart
description: Simple test menu
dependencies:
  tekartik_mdl_js:
    git: git://github.com/tekartik/mdl_js.dart
dev_dependencies:
  dev_test: any
  test: any