name: tekartik_test_menu
version: 0.4.5
homepage: https://github.com/tekartik/test_menu.dart
# git://github.com/tekartik/tekartik_test_menu.dart
description: Simple test menu
author: Alexandre Roux <alex@tekartik.com>
environment:
  sdk: '>=1.0.0 <2.0.0'
dependencies:
  func: any
  tekartik_mdl_js:
    git: git://github.com/tekartik/mdl_js.dart
    version: '>=0.4.0'
  dart_to_js_script_rewriter: any
  platform_context:
    git: git://github.com/tekartik/platform_context.dart
  tekartik_common_utils:
    git: git://github.com/tekartik/common_utils.dart
    version: '>=0.4.5'
  tekartik_pub:
    git: git://github.com/tekartik/pub.dart

dev_dependencies:
  grinder: any
  dev_test: any
  test: any
  tekartik_browser_utils:
    git: git://github.com/tekartik/browser_utils.dart
    version: '>=0.5.0'
  tekartik_deploy:
    git: git://github.com/tekartik/deploy.dart
  chrome_travis:
    git: git://github.com/tekartik/chrome_travis.dart
    version: '>=0.1.3'
transformers:
  - dart_to_js_script_rewriter

# try ddc
web:
  compiler:
    debug: dartdevc

dependency_overrides:
#  tekartik_mdl_js:
#    path: /opt/devx/git/github.com/alextekartik/mdl_js.dart
#  platform_context:
#    # path: /opt/devx/git/github.com/tekartik/platform_context.dart
#    path: /opt/devx/git/github.com/alextekartik/platform_context.dart