name: tekartik_test_menu_repo
description: Test menu repo (tools)
version: 0.6.0
publish_to: none
#homepage: https://www.example.com
#author: alex <email@example.com>

environment:
  sdk: '>=2.10.0-0 <3.0.0'

dev_dependencies:
  process_run: '>=0.10.0+1'
  dev_test:
  chrome_travis:
    git:
      url: git://github.com/tekartik/chrome_travis.dart
      ref: dart2
  tekartik_common_utils:
    git:
      url: git://github.com/tekartik/common_utils.dart
      ref: dart2
    version: '>=0.10.3'