name: tekartik_test_menu_io
version: 0.6.0
homepage: https://github.com/tekartik/test_menu.dart
# git://github.com/tekartik/tekartik_test_menu.dart
description: Simple io test menu
author: Alexandre Roux <alex@tekartik.com>
environment:
  sdk: '>=2.6.0 <3.0.0'
dependencies:
  tekartik_test_menu:
    git:
      url: git://github.com/tekartik/test_menu.dart
      ref: dart2
      path: test_menu
    version: '>=0.5.2'
#  tekartik_pub:
#    git:
#      url: git://github.com/tekartik/pub.dart
#      ref: dart2

dev_dependencies:
  process_run: '>=0.10.0+1'
  grinder: any
  dev_test: any
  test: any
  tekartik_deploy:
    git:
      url: git://github.com/tekartik/deploy.dart
      ref: dart2

dependency_overrides:
  tekartik_test_menu:
    path: ../test_menu

#  tekartik_mdl_js:
#    path: /opt/devx/git/github.com/alextekartik/mdl_js.dart
#  platform_context:
#    # path: /opt/devx/git/github.com/tekartik/platform_context.dart
#    path: /opt/devx/git/github.com/alextekartik/platform_context.dart