name: tekartik_test_menu_browser
version: 0.4.5
homepage: https://github.com/tekartik/test_menu.dart
# git://github.com/tekartik/tekartik_test_menu.dart
description: Simple test menu
author: Alexandre Roux <alex@tekartik.com>
environment:
  sdk: '>=2.0.0-dev.58 <3.0.0'
dependencies:
  func: any
  tekartik_test_menu:
    git:
      url: git://github.com/tekartik/test_menu.dart
      ref: dart2
      path: test_menu
  tekartik_mdl_js:
    git:
      url: git://github.com/tekartik/mdl_js.dart
      ref: dart2
    version: '>=0.4.0'
  tekartik_browser_utils:
    git:
      url: git://github.com/tekartik/browser_utils.dart
      ref: dart2
    version: '>=0.5.0'


dev_dependencies:
  grinder: any
  dev_test: any
  test: any
  tekartik_pub:
    git:
      url: git://github.com/tekartik/pub.dart
      ref: dart2
  chrome_travis:
    git:
      url: git://github.com/tekartik/chrome_travis.dart
      ref: dart2
    version: '>=0.1.3'
  tekartik_deploy:
    git:
      url: git://github.com/tekartik/deploy.dart
      ref: dart2
dependency_overrides:
  tekartik_test_menu:
    path: ../test_menu
  tekartik_test_menu_example:
      path: ../test_menu_example
#  tekartik_mdl_js:
#    path: /opt/devx/git/github.com/alextekartik/mdl_js.dart
#  platform_context:
#    # path: /opt/devx/git/github.com/tekartik/platform_context.dart
#    path: /opt/devx/git/github.com/alextekartik/platform_context.dart