name: tekartik_test_menu
version: 0.6.0
homepage: https://github.com/tekartik/test_menu.dart
# git://github.com/tekartik/tekartik_test_menu.dart
description: Simple test menu
author: Alexandre Roux <alex@tekartik.com>
publish_to: none

environment:
  sdk: '>=2.10.0-0 <3.0.0'
dependencies:
  tekartik_common_utils:
    git:
      url: git://github.com/tekartik/common_utils.dart
      ref: dart2
    version: '>=0.10.3'
  matcher: any
  meta: any

dev_dependencies:
  process_run: '>=0.10.0+1'
  grinder: any
  dev_test: any
  test: any
  tekartik_pub:
    git:
      url: git://github.com/tekartik/pub.dart
      ref: dart2
  tekartik_browser_utils:
    git:
      url: git://github.com/tekartik/browser_utils.dart
      ref: dart2
    version: '>=0.5.0'
  tekartik_deploy:
    git:
      url: git://github.com/tekartik/deploy.dart
      ref: dart2
  chrome_travis:
    git:
      url: git://github.com/tekartik/chrome_travis.dart
      ref: dart2
    version: '>=0.1.3'

dependency_overrides:
#  tekartik_mdl_js:
#    path: /opt/devx/git/github.com/alextekartik/mdl_js.dart
#  platform_context:
#    # path: /opt/devx/git/github.com/tekartik/platform_context.dart
#    path: /opt/devx/git/github.com/alextekartik/platform_context.dart