targets:
  $default:
    sources:
    - "lib/**"
    - "starter_browser_mdl/**"
    builders:
      build_web_compilers|entrypoint:
        # These are globs for the entrypoints you want to compile.
        generate_for:
        - starter_browser_mdl/**.dart
        - web/**.dart
        - example/**.dart
        - lib/**