name: tekartik_test_menu_example
version: 0.4.5
homepage: https://github.com/tekartik/test_menu.dart
# git://github.com/tekartik/tekartik_test_menu.dart
description: Simple test menu example
author: Alexandre Roux <alex@tekartik.com>
publish_to: none

environment:
  sdk: '>=2.3.0-dev <3.0.0'

dependencies:
  angular_test: ">=2.0.0"
  build_runner: ">=0.10.0"
  build_test: '>=0.10.2'
  build_web_compilers: ">=0.4.0"
  test: '>=1.0.0'

dev_dependencies:
  process_run: '>=0.10.0+1'

dependency_overrides:
  tekartik_test_menu_io:
    path: ../test_menu_io
  tekartik_test_menu_browser:
    path: ../test_menu_browser
  tekartik_test_menu:
      path: ../test_menu

#  tekartik_mdl_js:
#    path: /opt/devx/git/github.com/alextekartik/mdl_js.dart
#  platform_context:
#    # path: /opt/devx/git/github.com/tekartik/platform_context.dart
#    path: /opt/devx/git/github.com/alextekartik/platform_context.dart